apiVersion: v1
kind: Pod
metadata: 
  name: spring
spec: 
  containers:
    - name: spring
      image: venkatasaitejareddychalla/saiteja:spc
      ports:
        - containerPort: 8080
          hostPort: 8080 
          protocol: TCP
        